In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\D E L L\Desktop\dash\Final Project\cars_price.csv")

In [3]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [5]:
df.duplicated().sum()

0

In [6]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [7]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [8]:
df.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [9]:
df.nunique()

symboling              6
normalized-losses     52
make                  22
fuel-type              2
aspiration             2
num-of-doors           3
body-style             5
drive-wheels           3
engine-location        2
wheel-base            53
length                75
width                 44
height                49
curb-weight          171
engine-type            7
num-of-cylinders       7
engine-size           44
fuel-system            8
bore                  39
stroke                37
compression-ratio     32
horsepower            60
peak-rpm              24
city-mpg              29
highway-mpg           30
price                187
dtype: int64

In [10]:
df.shape

(205, 26)

In [11]:
df.iloc[:,-1].value_counts()

?        4
8921     2
18150    2
8845     2
8495     2
        ..
45400    1
16503    1
5389     1
6189     1
22625    1
Name: price, Length: 187, dtype: int64

In [12]:
for i in df.columns:
    print(f'{i},{df[i].value_counts()}')

symboling, 0    67
 1    54
 2    32
 3    27
-1    22
-2     3
Name: symboling, dtype: int64
normalized-losses,?      41
161    11
91      8
150     7
134     6
128     6
104     6
85      5
94      5
65      5
102     5
74      5
168     5
103     5
95      5
106     4
93      4
118     4
148     4
122     4
83      3
125     3
154     3
115     3
137     3
101     3
119     2
87      2
89      2
192     2
197     2
158     2
81      2
188     2
194     2
153     2
129     2
108     2
110     2
164     2
145     2
113     2
256     1
107     1
90      1
231     1
142     1
121     1
78      1
98      1
186     1
77      1
Name: normalized-losses, dtype: int64
make,toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
jaguar            3
chevrolet         3
alfa-romero       3
renault           2
mercury           1
Name: make, dtype: int64
fuel-type,gas       185
diesel     20
Name: fuel-type, dtype: int64
aspiration,std      168
turbo     37
Name: aspiration, dtype: int64
num-of-doors,four    114
two      89
?         2
Name: num-of-doors, dtype: int64
body-style,sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: body-style, dtype: int64
drive-wheels,fwd    120
rwd     76
4wd      9
Name: drive-wheels, dtype: int64
engine-location,front    202
rear       3
Name: engine-location, dtype: int64
wheel-base,94.5     21
93.7     20
95.7     13
96.5      8
97.3      7
98.4      7
104.3     6
100.4     6
107.9     6
98.8      6
99.1      6
96.3      6
109.1     5
93.1      5
97.2      5
95.9      5
102.4     5
97.0      4
95.3      4
114.2     4
101.2     4
110.0     3
103.5     3
89.5      3
105.8     3
96.1      2
102.9     2
104.5     2
91.3      2
96.9      2
88.6      2
113.0     2
99.8      2
115.6     2
103.3     2
86.6      2
104.9     2
93.3      1
99.4      1
99.5      1
88.4      1
94.3      1
96.0      1
95.1      1
93.0      1
102.0     1
106.7     1
108.0     1
96.6      1
99.2      1
112.0     1
102.7     1
120.9     1
Name: wheel-base, dtype: int64
length,157.3    15
188.8    11
171.7     7
186.7     7
166.3     7
         ..
165.6     1
187.5     1
180.3     1
208.1     1
199.2     1
Name: length, Length: 75, dtype: int64
width,63.8    24
66.5    23
65.4    15
63.6    11
64.4    10
68.4    10
64.0     9
65.5     8
65.2     7
64.2     6
66.3     6
65.6     6
67.2     6
67.9     5
66.9     5
65.7     4
68.9     4
64.8     4
63.9     3
70.3     3
71.7     3
71.4     3
65.0     3
68.3     2
67.7     2
64.1     2
66.1     2
69.6     2
64.6     2
72.0     1
68.0     1
70.5     1
61.8     1
66.0     1
62.5     1
70.6     1
72.3     1
66.6     1
63.4     1
60.3     1
70.9     1
66.4     1
66.2     1
68.8     1
Name: width, dtype: int64
height,50.8    14
52.0    12
55.7    12
54.1    10
54.5    10
55.5     9
56.7     8
54.3     8
52.6     7
56.1     7
51.6     7
53.0     6
52.8     6
54.9     6
50.2     6
53.7     5
55.1     5
50.6     5
49.6     4
58.7     4
53.3     4
52.5     3
59.1     3
56.2     3
49.7     3
57.5     3
53.5     3
54.4     2
53.9     2
56.3     2
50.5     2
59.8     2
56.5     2
54.7     2
48.8     2
49.4     2
51.4     2
51.0     1
54.8     1
55.4     1
56.0     1
55.2     1
53.2     1
47.8     1
55.9     1
52.4     1
55.6     1
53.1     1
58.3     1
Name: height, dtype: int64
curb-weight,2385    4
1918    3
2275    3
1989    3
2410    2
       ..
2370    1
2328    1
2833    1
2921    1
3062    1
Name: curb-weight, Length: 171, dtype: int64
engine-type,ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: engine-type, dtype: int64
num-of-cylinders,four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: num-of-cylinders, dtype: int64
engine-size,122    15
92     15
97     14
98     14
108    13
90     12
110    12
109     8
120     7
141     7
152     6
181     6
146     6
121     6
156     5
136     5
91      5
183     4
130     4
171     3
70      3
194     3
209     3
164     3
258     2
140     2
134     2
234     2
132     2
131     2
173     1
203     1
161     1
80      1
151     1
103     1
304     1
308     1
326     1
119     1
111     1
79      1
61      1
145     1
Name: engine-size, dtype: int64
fuel-system,mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: fuel-system, dtype: int64
bore,3.62    23
3.19    20
3.15    15
3.03    12
2.97    12
3.46     9
3.31     8
3.78     8
3.43     8
3.27     7
2.91     7
3.39     6
3.54     6
3.05     6
3.58     6
3.7      5
3.01     5
3.35     4
?        4
3.17     3
3.59     3
3.74     3
3.47     2
3.94     2
3.24     2
3.13     2
3.63     2
3.5      2
3.8      2
3.33     2
2.54     1
3.08     1
3.61     1
3.34     1
3.6      1
2.92     1
3.76     1
2.68     1
2.99     1
Name: bore, dtype: int64
stroke,3.4     20
3.23    14
3.15    14
3.03    14
3.39    13
2.64    11
3.29     9
3.35     9
3.46     8
3.11     6
3.27     6
3.41     6
3.07     6
3.58     6
3.19     6
3.5      6
3.64     5
3.52     5
3.86     4
3.54     4
3.47     4
?        4
3.9      3
2.9      3
3.1      2
4.17     2
2.8      2
2.19     2
3.08     2
2.68     2
2.36     1
3.16     1
2.07     1
3.21     1
3.12     1
2.76     1
2.87     1
Name: stroke, dtype: int64
compression-ratio,9.00     46
9.40     26
8.50     14
9.50     13
9.30     11
8.70      9
8.00      8
9.20      8
7.00      7
8.60      5
21.00     5
8.40      5
7.50      5
23.00     5
9.60      5
21.50     4
7.60      4
10.00     3
22.50     3
8.30      3
8.80      3
7.70      2
8.10      2
9.10      1
9.31      1
7.80      1
9.41      1
21.90     1
22.00     1
22.70     1
10.10     1
11.50     1
Name: compression-ratio, dtype: int64
horsepower,68     19
70     11
69     10
116     9
110     8
95      7
88      6
62      6
101     6
160     6
114     6
84      5
97      5
102     5
145     5
82      5
76      5
111     4
92      4
123     4
86      4
90      3
73      3
85      3
207     3
182     3
121     3
152     3
112     2
56      2
161     2
156     2
94      2
52      2
?       2
162     2
155     2
184     2
100     2
176     2
55      1
262     1
134     1
115     1
140     1
48      1
58      1
60      1
78      1
135     1
200     1
64      1
120     1
72      1
154     1
288     1
143     1
142     1
175     1
106     1
Name: horsepower, dtype: int64
peak-rpm,5500    37
4800    36
5000    27
5200    23
5400    13
6000     9
5250     7
4500     7
5800     7
4200     5
4150     5
4750     4
4350     4
5100     3
4250     3
5900     3
4400     3
?        2
6600     2
4650     1
5600     1
5750     1
4900     1
5300     1
Name: peak-rpm, dtype: int64
city-mpg,31    28
19    27
24    22
27    14
17    13
26    12
23    12
21     8
25     8
30     8
38     7
28     7
16     6
37     6
22     4
29     3
15     3
20     3
18     3
14     2
34     1
35     1
32     1
36     1
45     1
13     1
49     1
47     1
33     1
Name: city-mpg, dtype: int64
highway-mpg,25    19
38    17
24    17
30    16
32    16
34    14
37    13
28    13
29    10
33     9
22     8
31     8
23     7
27     5
43     4
42     3
26     3
41     3
19     2
39     2
18     2
16     2
20     2
36     2
47     2
46     2
54     1
17     1
53     1
50     1
Name: highway-mpg, dtype: int64
price,?        4
8921     2
18150    2
8845     2
8495     2
        ..
45400    1
16503    1
5389     1
6189     1
22625    1
Name: price, Length: 187, dtype: int64

In [13]:
import numpy as np
df.replace('?', np.nan, inplace = True)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    object
 22  peak-rpm           203 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

TOP 10 FEATURES FROM RFE
symboling
aspiration
num-of-doors
drive-wheels
engine-location
wheel-base
length
width
height
curb-weight

In [15]:
data=df.drop(['symboling','aspiration',
       'num-of-doors','drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight'],axis=1)

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   normalized-losses  164 non-null    object
 1   make               205 non-null    object
 2   fuel-type          205 non-null    object
 3   body-style         205 non-null    object
 4   engine-type        205 non-null    object
 5   num-of-cylinders   205 non-null    object
 6   engine-size        205 non-null    int64
 7   fuel-system        205 non-null    object
 8   bore               201 non-null    object
 9   stroke             201 non-null    object
 10  compression-ratio  205 non-null    float64
 11  horsepower         203 non-null    object
 12  peak-rpm           203 non-null    object
 13  city-mpg           205 non-null    int64
 14  highway-mpg        205 non-null    int64
 15  price              201 non-null    object
dtypes: float64(1), int64(3), object(12)
memory usage: 25.8+ KB

In [17]:
data.head()

,normalized-losses,make,fuel-type,body-style,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,NaN,alfa-romero,gas,convertible,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,NaN,alfa-romero,gas,convertible,dohc,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,NaN,alfa-romero,gas,hatchback,ohcv,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,164,audi,gas,sedan,ohc,four,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,164,audi,gas,sedan,ohc,five,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

HANDLING NULL VALUES

In [18]:
data.isnull().sum()

normalized-losses    41
make                  0
fuel-type             0
body-style            0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  164 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       203 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               201 non-null    object
 19  stroke             201 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         203 non-null    object
 22  peak-rpm           203 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              201 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [20]:
data['normalized-losses'] = pd.to_numeric(data['normalized-losses'])
data['horsepower'] = pd.to_numeric(data['horsepower'])
data['price'] = pd.to_numeric(data['price'])

In [21]:
from sklearn.impute import SimpleImputer
import numpy as np

SI = SimpleImputer(strategy='mean', missing_values=np.nan)
data['normalized-losses'] = SI.fit_transform(data[['normalized-losses']])
data['horsepower'] = SI.fit_transform(data[['horsepower']])
data['price'] = SI.fit_transform(data[['price']])

In [22]:
data.isnull().sum()

normalized-losses    0
make                 0
fuel-type            0
body-style           0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           0
peak-rpm             2
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   normalized-losses  205 non-null    float64
 1   make               205 non-null    object
 2   fuel-type          205 non-null    object
 3   body-style         205 non-null    object
 4   engine-type        205 non-null    object
 5   num-of-cylinders   205 non-null    object
 6   engine-size        205 non-null    int64
 7   fuel-system        205 non-null    object
 8   bore               201 non-null    object
 9   stroke             201 non-null    object
 10  compression-ratio  205 non-null    float64
 11  horsepower         205 non-null    float64
 12  peak-rpm           203 non-null    object
 13  city-mpg           205 non-null    int64
 14  highway-mpg        205 non-null    int64
 15  price              205 non-null    float64
dtypes: float64(4), int64(3), object(9)
memory usage: 25.8+ KB

In [24]:
data['make'].value_counts()

toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
jaguar            3
chevrolet         3
alfa-romero       3
renault           2
mercury           1
Name: make, dtype: int64

In [25]:
data['fuel-type'].value_counts()

gas       185
diesel     20
Name: fuel-type, dtype: int64

In [26]:
data['aspiration'].value_counts()

KeyError: 'aspiration'

In [ ]:
data['body-style'].value_counts()

In [ ]:
data['num-of-cylinders'].value_counts()

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
OE=OrdinalEncoder()

In [ ]:
data['make']=OE.fit_transform(data[['make']])
data['fuel-type']=OE.fit_transform(data[['fuel-type']])
data['aspiration']=OE.fit_transform(data[['aspiration']])
data['body-style']=OE.fit_transform(data[['body-style']])
data['num-of-cylinders']=OE.fit_transform(data[['num-of-cylinders']])

In [ ]:
data

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Set the figure size
plt.figure(figsize=(12, 12))  

sns.boxplot(data.iloc[:, :-1])
plt.xticks(rotation='vertical')
plt.show()

In [ ]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [ ]:
X.shape

In [ ]:
y.shape

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 5)

In [ ]:
# For train data
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
tX_train=ss.fit_transform(X_train)

In [ ]:
# For test data
tX_test=ss.transform(X_test)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

In [ ]:
from sklearn.linear_model import SGDRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
lr = LinearRegression()
lr.fit(tX_train, y_train)
print(lr.score(tX_train, y_train))
print(lr.score(tX_test, y_test))

In [ ]:
dtr=DecisionTreeRegressor()
dtr.fit(tX_train,y_train)
print(dtr.score(tX_train,y_train))
print(dtr.score(tX_test, y_test))

In [ ]:
sgr=SGDRegressor()
sgr.fit(tX_train,y_train)
print(sgr.score(tX_train,y_train))
print(sgr.score(tX_test, y_test))

In [ ]:
rfr = RandomForestRegressor()
rfr.fit(tX_train, y_train)
print(rfr.score(tX_train, y_train))
print(rfr.score(tX_test, y_test))

In [ ]:
gbr=GradientBoostingRegressor()
gbr.fit(tX_train, y_train)
print(gbr.score(tX_train, y_train))
print(gbr.score(tX_test, y_test))

In [ ]:
# select DecisionTreeRegressor as the final model.
final_model = rfr

In [ ]:
y_pred = final_model.predict(tX_test)

In [ ]:
from sklearn import metrics
metrics.mean_squared_error(y_test,y_pred)

In [ ]:
metrics.mean_absolute_error(y_test, y_pred)

In [ ]:
print(metrics.r2_score(y_test,y_pred))

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

# Regularized linear regression
ridge = Ridge()
parameters = {'alpha': [0.1, 1.0, 10.0]}  
grid_search = GridSearchCV(ridge, parameters, cv=5)
grid_search.fit(tX_train, y_train)

# Evaluate model performance
best_ridge = grid_search.best_estimator_
train_score = best_ridge.score(tX_train, y_train)
test_score = best_ridge.score(tX_test, y_test)

print("Train Score Ridge linear Regression:" ,train_score)
print("Test Score Ridge linear Regression:",test_score)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV

dtr = DecisionTreeRegressor()

# Define the hyperparameters 
param_grid = {
    'max_depth': [None, 5, 10],  # Maximum depth 
    'min_samples_split': [2, 5, 10],  # Minimum number of samples 
    'min_samples_leaf': [1, 2, 4],  # Minimum number of samples required at leaf node
}

# Perform GridSearchCV to find the best hyperparameters
grid_search = GridSearchCV(dtr, param_grid, cv=5)
grid_search.fit(tX_train, y_train)

# best estimator
best_dtr = grid_search.best_estimator_

# model performance
train_score = best_dtr.score(tX_train, y_train)
test_score = best_dtr.score(tX_test, y_test)

print("Train Score decision tree: ",train_score)
print("Test Score decision tree: ",test_score)

In [ ]:
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import GridSearchCV

sgr = SGDRegressor()

# Define the hyperparameters 
param_grid = {
    'alpha': [0.0001, 0.001, 0.01],  # Regularization parameter
    'max_iter': [1000, 2000, 3000],  
    'learning_rate': ['constant', 'adaptive'],  
}

# Perform GridSearchCV to find the best hyperparameters
grid_search = GridSearchCV(sgr, param_grid, cv=5)
grid_search.fit(tX_train, y_train)

# Get the best estimator
best_sgr = grid_search.best_estimator_

# Evaluate model performance
train_score = best_sgr.score(tX_train, y_train)
test_score = best_sgr.score(tX_test, y_test)

print("Train Score SGD regressor: ",train_score)
print("Test Score SGD regressor: ",test_score)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

rfr = RandomForestRegressor()

# Define the hyperparameters 
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_depth': [None, 5, 10],  # Maximum depth 
    'min_samples_split': [2, 5, 10],  # Minimum number of samples to split an internal node
    'min_samples_leaf': [1, 2, 4],  # Minimum number of samples required to be at a leaf node
}

grid_search = GridSearchCV(rfr, param_grid, cv=5)
grid_search.fit(tX_train, y_train)

# Get the best estimator
best_rfr = grid_search.best_estimator_

# Evaluate model performance
train_score = best_rfr.score(tX_train, y_train)
test_score = best_rfr.score(tX_test, y_test)

print("Train Score Random Forest regressor: ",train_score)
print("Test Score Random Forest regressor: ",test_score)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV

gbr=GradientBoostingRegressor()

# Define the hyperparameters
param_grid={
    'n_estimators':[100,200,300],
    'max_depth':[None,5,10],
    'min_samples_split':[2,5,10],
    'min_samples_leaf':[1,2,4]
}

grid_search=GridSearchCV(gbr,param_grid,cv=5)
grid_search.fit(tX_train,y_train)

# Get the best estimator
best_gbr=grid_search.best_estimator_

# Evaluate model performance
train_score=best_gbr.score(tX_train,y_train)
test_score=best_gbr.score(tX_test,y_test)

print("Train Score Gradient Boost regressor: ",train_score)
print("Test Score Gradient Boost regressor: ",test_score)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

# Create the pipeline
pipeline = Pipeline([
    ('scaler', StandardScaler()),  # Feature scaling
    ('gbr', GradientBoostingRegressor())  # GradientBoostingRegressor 
])

# Define the hyperparameters 
param_grid = {
    'gbr__n_estimators': [100, 200, 300],  
    'gbr__learning_rate': [0.1, 0.01, 0.001],  
    'gbr__max_depth': [3, 5, 7],  
    'gbr__min_samples_split': [2, 5, 10],  
    'gbr__min_samples_leaf': [1, 2, 4],  
}

# Perform GridSearchCV 
grid_search = GridSearchCV(pipeline, param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Get the best estimator
best_model = grid_search.best_estimator_

# Evaluate model performance
train_score = best_model.score(X_train, y_train)
test_score = best_model.score(X_test, y_test)


print("Train Score Gradient Boost regressor: ",train_score)
print("Test Score Gradient Boost regressor: ",test_score)